import time

x = float(input("Input seconds delay following script:\n>"))
if x > 10:
    print("dum bass pick a faster rate")

def sleep(x):
    time.sleep(x)


def enter():
    x = "\n"
    print(x*50)
def senter():
    sleep()
    enter()
sleep(x)
print("*darkness*")
enter()
sleep(x)
print("...silence")
sleep(x)
print(f"Y/N: ...Where am I?")
sleep(x)
print("🔥💥💥💥💥💥🔥🔥🔥🔥🔥🔥🔥🔥🤯🤯")
sleep(x)
print("*Floor Rumbles*")
sleep(x)
print("*MORE RAIN*")
sleep(x)
print("*FLOOR CRACKS* 💥💥💥💥💥")
sleep(x)
print(f"Y/N: ❗❗")
sleep(x)
print("*A blue whirling entity spawned beneath you*")
sleep(x)
print("*As you fell through the floor, you were engulfed by the portal.*")
sleep(x)
print("*You blacked out*")
sleep(x)
print("- - - - - - - - - - - - - - - - - -")
sleep(x)
print("???: ?olleH")
sleep(x)
print("*??????*")
sleep(x)
print("???: !!pu ekaW")
sleep(x)
print("???: !!WON pu ekaW")
sleep(x)
print("*You wake up on wet floor*")
sleep(x)
begin = input("[1] > Who are you?\n[2] > Where am I?\n>")
if begin == "1":
    print("???: I am a nymph and I'm helping you on your journey")
    sleep(x)
    print(f"Y/N: Interesting...")
    sleep(x)
    force = input("[2] > Where am I?\n>")
    print("Nymph: You are currently in alternate dimension 2000 years into the future!")
    sleep(x)
    print(f"Y/N: What the flip??")
    
elif begin == "2":
    print("???: You are currently in alternate dimension 2000 years into the future!")
    sleep(x)
    print(f"Y/N: What the flip??")
    sleep(x)
    force2 = input("[1] > Who are you?\n>")
    print("???: I am a nymph and I'm helping you on your journey")
    sleep(x)
    print(f"Y/N: Interesting...")
sleep(x)
print(f"Y/N: What do we do now?")
sleep(x)
print("Nymph: You have to go through 25 worlds and battle enemies until you reach boss.")
sleep(x)
print(f"Y/N: And what does the boss look like?")
sleep(x)
print("Nymph: You'll know it when you see it...")
sleep(x)
print(f"Y/N: Doesn't help that much")
sleep(x)
print("Nymph: Well I gotta go now. I might visit, but for now, goodbye!")
sleep(x)
print(f"Y/N: NO WAIT-")
sleep(x)
print("✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨")
sleep(.5)
print("*You are now in Mainlands, use W,A,S,D to move*")
sleep(1)
print(f"Y/N: Ok, what do I do now...")
sleep(.5)